### ISSUE TITLE
BUG UPD 描述符举例的问题

### ISSUE THREAD

**Issue by juruo888** [class-tools/CTGitCommitMsgStd#2]
Description: `UPD 1919810001` 表示在 `1919` 年 `81` 月 `00` 日的第 `01` 次提交，但是 `81` 月和 `00` 日显然是不存在的。

**Comment by hjl2011** [comment]
那只是个举例 。。。

**Comment by hjl2011** [comment]
> Description: `UPD 1919810001` 表示在 `1919` 年 `81` 月 `00` 日的第 `01` 次提交，但是 `81` 月和 `00` 日显然是不存在的。

那只是个举例 。。。

**Comment by ren-yc** [comment]
欢迎 PR。

~~我懒得改了。~~

**Comment by juruo888** [comment]
已提交 PR

**Comment by juruo888** [comment]
Fixed.

https://github.com/class-tools/CTGitCommitMsgStd/commit/18752c0b4144baaae52435a4589d1b8deb20da3b
